id: I1F87CF44
source: https://library.bdrc.io
source_file: null
initial_creation_type: ocr
imported: '2020-03-23T09:21:10+00:00'
last_modified: '2022-06-07T21:05:21.863986+00:00'
parser: https://github.com/OpenPecha-dev/openpecha-toolkit/blob/231bba39dd1ba393320de82d4d08a604aabe80fc/openpecha/formatters/google_orc.py
source_metadata:
  id: bdr:W1KG25012
  title: སུམ་རྟགས་སྙན་གསུམ་གྱི་རྩ་བ།
  author: ''
  access: http://purl.bdrc.io/admindata/AccessOpen
  restrictedInChina: false
  base:
    E9FE:
      image_group_id: I1KG25014
      title: ''
      total_pages: 132
      order: 1
      base_file: E9FE.txt
statistics: {}
quality: {}
copyright:
  status: Unknown
  notice: ''
  info_url: null
license: null
