id: P004209
initial_creation_type: ocr
created_at: 23/03/2020
last_modified_at: 2021-12-17 11:01:18.012846
source_metadata:
  id: bdr:W1KG25012
  title: སུམ་རྟགས་སྙན་གསུམ་གྱི་རྩ་བ།
  author: ''
  volumes:
    eba0b979cbaa4b86a824a340489416ba:
      image_group_id: I1KG25014
      title: ''
      volume_number: 1
      total_pages: 132
      base_file: v001.txt
  access: http://purl.bdrc.io/admindata/AccessOpen
  restrictedInChina: false
