id: P004209
initial_creation_type: ocr
source_metadata:
  id: bdr:W1KG25012
  title: སུམ་རྟགས་སྙན་གསུམ་གྱི་རྩ་བ།
  author: ''
  volumes:
    eba0b979cbaa4b86a824a340489416ba:
      image_group_id: I1KG25014
      title: ''
      volume_number: 1
      total_pages: 132
